insert into marca (nombre_marca) values ('Dell');
insert into marca (nombre_marca) values ('Lenovo');
insert into marca (nombre_marca) values ('HP');
insert into marca (nombre_marca) values ('Apple');
insert into marca (nombre_marca) values ('Asus');
insert into marca (nombre_marca) values ('Epson');
insert into marca (nombre_marca) values ('Acer');
insert into marca (nombre_marca) values ('Samsung');
insert into marca (nombre_marca) values ('Brother');
insert into marca (nombre_marca) values ('Toshiba');
insert into marca (nombre_marca) values ('Sony');
insert into marca (nombre_marca) values ('Gigabyte');
insert into marca (nombre_marca) values ('Corsair');
insert into marca (nombre_marca) values ('Razer');
insert into marca (nombre_marca) values ('Logitech');
insert into marca (nombre_marca) values ('Western Digital');
insert into marca (nombre_marca) values ('Seagate');
insert into marca (nombre_marca) values ('Kingston');
insert into marca (nombre_marca) values ('Intel');
insert into marca (nombre_marca) values ('AMD');
insert into marca (nombre_marca) values ('Nvidia');
insert into marca (nombre_marca) values ('Zotac');
insert into marca (nombre_marca) values ('Sapphire');
insert into marca (nombre_marca) values ('ASRock');
insert into marca (nombre_marca) values ('NZXT');
insert into marca (nombre_marca) values ('Thermaltake');
insert into marca (nombre_marca) values ('Cooler Master');
insert into marca (nombre_marca) values ('be quiet!');
insert into marca (nombre_marca) values ('Noctua');
insert into marca (nombre_marca) values ('Fractal Design');
insert into marca (nombre_marca) values ('Lian Li');
insert into marca (nombre_marca) values ('G.Skill');
insert into marca (nombre_marca) values ('ADATA');
insert into marca (nombre_marca) values ('PNY');
insert into marca (nombre_marca) values ('Lexar');
insert into marca (nombre_marca) values ('Transcend');
insert into marca (nombre_marca) values ('Biostar');
insert into marca (nombre_marca) values ('Xiaomi');
insert into marca (nombre_marca) values ('Huawei');
insert into marca (nombre_marca) values ('Honor');
insert into marca (nombre_marca) values ('Motorola');
insert into marca (nombre_marca) values ('Nokia');
insert into marca (nombre_marca) values ('BenQ');
insert into marca (nombre_marca) values ('ViewSonic');
insert into marca (nombre_marca) values ('AOC');
insert into marca (nombre_marca) values ('Alienware');
insert into marca (nombre_marca) values ('Predator');
insert into marca (nombre_marca) values ('ROG');
insert into marca (nombre_marca) values ('Aorus');
insert into marca (nombre_marca) values ('HyperX');
insert into marca (nombre_marca) values ('SteelSeries');
insert into marca (nombre_marca) values ('Wacom');
insert into marca (nombre_marca) values ('Garmin');
insert into marca (nombre_marca) values ('Fitbit');
insert into marca (nombre_marca) values ('Bose');

insert into tipo_dispositivo (nombre, descripcion) values ('Notebook', 'Equipo portatil de uso personal o corporativo');
insert into tipo_dispositivo (nombre, descripcion) values ('Desktop', 'Computador de escritorio torre tradicional');
insert into tipo_dispositivo (nombre, descripcion) values ('All-in-One', 'Equipo de escritorio integrado en pantalla');
insert into tipo_dispositivo (nombre, descripcion) values ('Servidor Rack', 'Servidor corporativo para montaje en gabinete');
insert into tipo_dispositivo (nombre, descripcion) values ('Monitor', 'Pantalla externa para estaciones de trabajo');
insert into tipo_dispositivo (nombre, descripcion) values ('Impresora', 'Dispositivo de impresion termica o inyeccion');
insert into tipo_dispositivo (nombre, descripcion) values ('Workstation', 'Estacion de trabajo para diseno o renderizado');
insert into tipo_dispositivo (nombre, descripcion) values ('Tablet', 'Dispositivo portatil tactil multiproposito');

insert into comuna (nombre_comuna) values ('Santiago');
insert into comuna (nombre_comuna) values ('Providencia');
insert into comuna (nombre_comuna) values ('Las Condes');
insert into comuna (nombre_comuna) values ('La Florida');
insert into comuna (nombre_comuna) values ('Maipu');
insert into comuna (nombre_comuna) values ('Nunoa');
insert into comuna (nombre_comuna) values ('San Miguel');
insert into comuna (nombre_comuna) values ('Macul');
insert into comuna (nombre_comuna) values ('Puente Alto');
insert into comuna (nombre_comuna) values ('Huechuraba');

insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (18452369, '4', 'Matias', 'Gonzalez', 987654321, 'mgonzalez@gmail.com', 'Av. Providencia 1345');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (15987452, 'K', 'Camila', 'Silva', 976543210, 'csilva.consultora@outlook.com', 'Los Leones 220 Depto 402');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (19321456, '8', 'Rodrigo', 'Perez', 965432109, 'rodrigo.perez@empresa.cl', 'Av. Apoquindo 4500');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (17654982, '1', 'Valentina', 'Rojas', 954321098, 'vrojas.diseno@gmail.com', 'Vicuna Mackenna 7200');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (16234890, '3', 'Sebastian', 'Munoz', 943210987, 'smunoz.ing@gmail.com', 'Av. Pajaritos 3100');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (14567123, '7', 'Francisca', 'Morales', 932109876, 'fmorales.abogada@gmail.com', 'Irarrazaval 2400');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (20123789, '2', 'Diego', 'Castro', 921098765, 'dcastro.dev@yahoo.com', 'Gran Avenida 5100');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (76234891, '5', 'Inversiones', 'Tecnologicas SpA', 912345678, 'contacto@invertec.cl', 'El Golf 40 Piso 12');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (13890456, '9', 'Alejandro', 'Vargas', 981234567, 'avargas.arq@gmail.com', 'Quilin 3400');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (17123987, '6', 'Loreto', 'Fernandez', 972345678, 'lfernandez.psico@gmail.com', 'Pedro Fontova 6200');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (77564120, '3', 'Servicios', 'Logisticos Central', 963456789, 'soporte@logcentral.cl', 'Americo Vespucio 1020');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (18890234, '5', 'Gabriel', 'Santander', 954567890, 'gsantander@hotmail.com', 'Concha y Toro 150');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (11234567, '8', 'Juan', 'Diaz', 911112222, 'jdiaz.tech@gmail.com', 'Av. Libertad 123');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (12345678, '5', 'Maria', 'Soto', 922223333, 'msoto@hotmail.com', 'Calle Los Pinos 45');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (13456789, '1', 'Pedro', 'Contreras', 933334444, 'pcontreras88@yahoo.com', 'Pasaje Las Rosas 678');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (14567890, '7', 'Ana', 'Martinez', 944445555, 'amartinez.arq@gmail.com', 'Av. Brasil 890');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (15678901, '9', 'Luis', 'Sepulveda', 955556666, 'lsepulveda.ing@gmail.com', 'San Martin 234');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (16789012, '3', 'Carmen', 'Rodriguez', 966667777, 'crodriguez@outlook.com', 'Av. Independencia 567');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (17890123, '9', 'Jose', 'Lopez', 977778888, 'jlopez.dg@gmail.com', 'Arturo Prat 890');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (18901234, '2', 'Laura', 'Fuentes', 988889999, 'lfuentes@empresa.cl', 'Alameda 1020');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (19012345, 'K', 'Carlos', 'Hernandez', 999990000, 'chernandez@gmail.com', 'Bulnes 450');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (20123456, '6', 'Daniela', 'Torres', 912121212, 'dtorres.abogada@gmail.com', 'Compania de Jesus 1500');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (21234567, '1', 'Miguel', 'Araya', 923232323, 'maraya@hotmail.com', 'Bandera 340');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (22345678, '8', 'Andrea', 'Flores', 934343434, 'aflores.med@gmail.com', 'Agustinas 980');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (23456789, '4', 'Jorge', 'Espinoza', 945454545, 'jespinoza@yahoo.cl', 'Huérfanos 1052');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (24567890, '8', 'Valeria', 'Valenzuela', 956565656, 'vvalenzuela@gmail.com', 'Moneda 812');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (25678901, '7', 'Francisco', 'Castillo', 967676767, 'fcastillo.arq@outlook.com', 'Teatinos 251');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (11345678, '4', 'Natalia', 'Gutierrez', 978787878, 'ngutierrez@gmail.com', 'Estado 360');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (12456789, '1', 'Pablo', 'Pizarro', 989898989, 'ppizarro.dev@gmail.com', 'San Antonio 427');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (13567890, '5', 'Sofia', 'Alvarez', 990909090, 'salvarez.design@gmail.com', 'Mac Iver 225');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (14678901, 'K', 'Claudio', 'Vasquez', 913131313, 'cvasquez@empresa.cl', 'Amunategui 277');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (15789012, '3', 'Camila', 'Sanchez', 924242424, 'csanchez.nutri@gmail.com', 'Tucapel Jimenez 56');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (16890123, '9', 'Andres', 'Ramirez', 935353535, 'aramirez@hotmail.com', 'San Diego 134');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (17901234, '2', 'Isidora', 'Carrasco', 946464646, 'icarrasco.vet@gmail.com', 'Nataniel Cox 200');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (18012345, '6', 'Fernando', 'Gomez', 957575757, 'fgomez.ing@gmail.com', 'Zenteno 120');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (19123456, '1', 'Javiera', 'Cortes', 968686868, 'jcortes@yahoo.com', 'Lord Cochrane 146');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (20234567, '5', 'Diego', 'Herrera', 979797979, 'dherrera@gmail.com', 'Aldunate 1020');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (21345678, '1', 'Paula', 'Nunez', 980808080, 'pnunez.arq@outlook.com', 'Eyzaguirre 1120');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (22456789, '6', 'Felipe', 'Jara', 991919191, 'fjara@empresa.cl', 'Copiapo 500');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (23567890, 'K', 'Catalina', 'Vergara', 914141414, 'cvergara@gmail.com', 'Aconcagua 345');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (24678901, '1', 'Tomas', 'Rivera', 925252525, 'trivera.dev@gmail.com', 'Santa Isabel 230');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (25789012, '7', 'Constanza', 'Figueroa', 936363636, 'cfigueroa.kine@gmail.com', 'Marin 124');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (11456789, '1', 'Nicolas', 'Riquelme', 947474747, 'nriquelme@hotmail.com', 'Victoria 850');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (12567890, '3', 'Macarena', 'Garcia', 958585858, 'mgarcia.psico@gmail.com', 'Matta 1250');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (13678901, '4', 'Ignacio', 'Miranda', 969696969, 'imiranda@yahoo.cl', 'Santa Rosa 900');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (14789012, '8', 'Rocio', 'Bravo', 970707070, 'rbravo.diseno@gmail.com', 'Lira 450');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (15890123, '1', 'Benjamin', 'Vera', 981818181, 'bvera.arq@gmail.com', 'Carmen 600');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (16901234, '5', 'Belen', 'Moya', 992929292, 'bmoya@outlook.com', 'San Isidro 120');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (17012345, '8', 'Joaquin', 'Salazar', 915151515, 'jsalazar.dev@gmail.com', 'Santa Victoria 345');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (18123456, '3', 'Paz', 'Orellana', 926262626, 'porellana@empresa.cl', 'Argomedo 432');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (19234567, '7', 'Samuel', 'Pardo', 937373737, 'spardo@gmail.com', 'Lira 780');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (20345678, '2', 'Antonia', 'Bustos', 948484848, 'abustos.med@gmail.com', 'Portugal 900');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (21456789, '6', 'Matias', 'Guzman', 959595959, 'mguzman.ing@hotmail.com', 'Diagonal Paraguay 450');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (22567890, '9', 'Florencia', 'Campos', 960606060, 'fcampos@gmail.com', 'Rancagua 234');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (23678901, '3', 'Vicente', 'Mendez', 971717171, 'vmendez.arq@yahoo.com', 'Seminario 567');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (24789012, '7', 'Josefina', 'Cardenas', 982828282, 'jcardenas@outlook.com', 'Bilbao 1020');
insert into cliente (rut_cliente, dv_rut, nombre, apellido, telefono, correo, direccion) values (25890123, '1', 'Cristobal', 'Navarro', 993939393, 'cnavarro@empresa.cl', 'Pedro de Valdivia 345');

insert into estado_orden (nombre, descripcion) values ('Recibido', 'Orden ingresada en sucursal a la espera de evaluacion');
insert into estado_orden (nombre, descripcion) values ('Pendiente de diagnostico', 'Equipo en cola asignado o por asignar a tecnico');
insert into estado_orden (nombre, descripcion) values ('Diagnosticado', 'Diagnostico tecnico emitido a la espera de presupuesto');
insert into estado_orden (nombre, descripcion) values ('Esperando aprobacion', 'Presupuesto enviado al cliente pendiente de respuesta');
insert into estado_orden (nombre, descripcion) values ('Esperando repuesto', 'Reparacion pausada por falta de insumo o importacion');
insert into estado_orden (nombre, descripcion) values ('En reparacion', 'Trabajo mecanico o electronico en ejecucion');
insert into estado_orden (nombre, descripcion) values ('Reparacion finalizada', 'Equipo reparado y con control de calidad aprobado');
insert into estado_orden (nombre, descripcion) values ('Entregado', 'Equipo devuelto conforme al cliente con orden cerrada');
insert into estado_orden (nombre, descripcion) values ('Reparacion rechazada', 'Presupuesto no aceptado o equipo catalogado como irreparable');
insert into estado_orden (nombre, descripcion) values ('Cancelado', 'Servicio anulado antes de iniciar trabajos tecnicos');

insert into especialidad (nombre_especialidad, descripcion) values ('Microelectronica', 'Reparacion de placas madre y circuitos smd');
insert into especialidad (nombre_especialidad, descripcion) values ('Sistemas y Software', 'Recuperacion forense de datos y configuracion so');
insert into especialidad (nombre_especialidad, descripcion) values ('Hardware General', 'Cambio de partes mecanicas pantallas y mantencion');
insert into especialidad (nombre_especialidad, descripcion) values ('Equipos de Impresion', 'Calibracion de cabezales y sistemas de arrastre');
insert into especialidad (nombre_especialidad, descripcion) values ('Servidores y Redes', 'Mantenimiento de storage fuentes redundantes y raid');

insert into repuesto (nombre_repuesto, descripcion, stock_disponible, stock_minimo) values ('SSD NVMe 1TB Kingston', 'Unidad m.2 PCIe Gen 4 corporativo', 18, 5);
insert into repuesto (nombre_repuesto, descripcion, stock_disponible, stock_minimo) values ('Pantalla LED 15.6 FHD', 'Display 30 pines compatible Dell y HP', 8, 3);
insert into repuesto (nombre_repuesto, descripcion, stock_disponible, stock_minimo) values ('Memoria RAM DDR4 16GB 3200MHz', 'Modulo sodimm para estaciones de trabajo', 24, 6);
insert into repuesto (nombre_repuesto, descripcion, stock_disponible, stock_minimo) values ('Pasta Termica Noctua 3.5g', 'Compuesto termico de alta conductividad', 20, 5);
insert into repuesto (nombre_repuesto, descripcion, stock_disponible, stock_minimo) values ('Bateria A1965 Apple', 'Modulo recargable original MacBook Air', 2, 4);
insert into repuesto (nombre_repuesto, descripcion, stock_disponible, stock_minimo) values ('Cabezal de Impresion Epson L Series', 'Repuesto cabezal micropiezo inyeccion continua', 5, 2);
insert into repuesto (nombre_repuesto, descripcion, stock_disponible, stock_minimo) values ('Teclado retroiluminado Lenovo', 'Teclado idioma espanol linea ThinkPad E14', 11, 3);
insert into repuesto (nombre_repuesto, descripcion, stock_disponible, stock_minimo) values ('Fuente de Poder ATX 650W Bronze', 'Unidad de alimentacion certificada desktop', 6, 2);
insert into repuesto (nombre_repuesto, descripcion, stock_disponible, stock_minimo) values ('SSD SATA 480GB Crucial', 'Unidad estado solido 2.5 pulgadas', 15, 4);
insert into repuesto (nombre_repuesto, descripcion, stock_disponible, stock_minimo) values ('Memoria RAM DDR5 16GB 4800MHz', 'Modulo sodimm nueva generacion portatil', 7, 3);
insert into repuesto (nombre_repuesto, descripcion, stock_disponible, stock_minimo) values ('Cooler Disipador HP Pavilion', 'Ventilador interno original linea gaming', 4, 2);
insert into repuesto (nombre_repuesto, descripcion, stock_disponible, stock_minimo) values ('Kit Rodillos Arrastre Brother', 'Gomas de alimentacion de papel multiproposito', 9, 3);

insert into bono_equipos_reparados (rango_minimo, rango_maximo, porc_bono) values (1, 5, 3);
insert into bono_equipos_reparados (rango_minimo, rango_maximo, porc_bono) values (6, 10, 5);
insert into bono_equipos_reparados (rango_minimo, rango_maximo, porc_bono) values (11, 20, 7);
insert into bono_equipos_reparados (rango_minimo, rango_maximo, porc_bono) values (21, 999, 10);

insert into modelo (nombre_modelo, id_marca) values ('Latitude 5420', 1);
insert into modelo (nombre_modelo, id_marca) values ('ThinkPad E14 Gen 3', 2);
insert into modelo (nombre_modelo, id_marca) values ('ProBook 450 G8', 3);
insert into modelo (nombre_modelo, id_marca) values ('MacBook Air M1', 4);
insert into modelo (nombre_modelo, id_marca) values ('EcoTank L3250', 6);
insert into modelo (nombre_modelo, id_marca) values ('OptiPlex 7090 Desktop', 1);
insert into modelo (nombre_modelo, id_marca) values ('ZenBook 14 UX425', 5);
insert into modelo (nombre_modelo, id_marca) values ('Aspire 5 A515', 7);
insert into modelo (nombre_modelo, id_marca) values ('DCP-T720DW', 9);
insert into modelo (nombre_modelo, id_marca) values ('PowerEdge R440', 1);
insert into modelo (nombre_modelo, id_marca) values ('MacBook Pro M2 14', 4);
insert into modelo (nombre_modelo, id_marca) values ('Pavilion Gaming 15', 3);

insert into modelo (nombre_modelo, id_marca) values ('PlayStation 5', 11);
insert into modelo (nombre_modelo, id_marca) values ('Aero 15 OLED', 12);
insert into modelo (nombre_modelo, id_marca) values ('K95 RGB Platinum', 13);
insert into modelo (nombre_modelo, id_marca) values ('Blade 15 Advanced', 14);
insert into modelo (nombre_modelo, id_marca) values ('MX Master 3S', 15);
insert into modelo (nombre_modelo, id_marca) values ('Black SN850X 1TB', 16);
insert into modelo (nombre_modelo, id_marca) values ('BarraCuda 2TB', 17);
insert into modelo (nombre_modelo, id_marca) values ('Fury Beast 16GB', 18);
insert into modelo (nombre_modelo, id_marca) values ('Core i9-13900K', 19);
insert into modelo (nombre_modelo, id_marca) values ('Ryzen 9 7950X', 20);
insert into modelo (nombre_modelo, id_marca) values ('GeForce RTX 4090', 21);
insert into modelo (nombre_modelo, id_marca) values ('Gaming Trinity OC', 22);
insert into modelo (nombre_modelo, id_marca) values ('Nitro+ Radeon RX 7900 XTX', 23);
insert into modelo (nombre_modelo, id_marca) values ('B650E Taichi', 24);
insert into modelo (nombre_modelo, id_marca) values ('H510 Elite', 25);
insert into modelo (nombre_modelo, id_marca) values ('Toughpower GF3 850W', 26);
insert into modelo (nombre_modelo, id_marca) values ('Hyper 212 Black Edition', 27);
insert into modelo (nombre_modelo, id_marca) values ('Dark Rock Pro 4', 28);
insert into modelo (nombre_modelo, id_marca) values ('NH-D15 chromax.black', 29);
insert into modelo (nombre_modelo, id_marca) values ('Meshify C', 30);
insert into modelo (nombre_modelo, id_marca) values ('O11 Dynamic EVO', 31);
insert into modelo (nombre_modelo, id_marca) values ('Trident Z5 Neo', 32);
insert into modelo (nombre_modelo, id_marca) values ('XPG Spectrix D41', 33);
insert into modelo (nombre_modelo, id_marca) values ('CS900 500GB SSD', 34);
insert into modelo (nombre_modelo, id_marca) values ('NM800 Pro 1TB', 35);
insert into modelo (nombre_modelo, id_marca) values ('StoreJet 25M3C', 36);
insert into modelo (nombre_modelo, id_marca) values ('B450MH', 37);
insert into modelo (nombre_modelo, id_marca) values ('Mi Notebook Pro 15', 38);
insert into modelo (nombre_modelo, id_marca) values ('MateBook X Pro 2022', 39);
insert into modelo (nombre_modelo, id_marca) values ('MagicBook 14', 40);
insert into modelo (nombre_modelo, id_marca) values ('Edge 40 Pro', 41);
insert into modelo (nombre_modelo, id_marca) values ('G21', 42);
insert into modelo (nombre_modelo, id_marca) values ('Mobiuz EX2710S', 43);
insert into modelo (nombre_modelo, id_marca) values ('Elite XG270QG', 44);
insert into modelo (nombre_modelo, id_marca) values ('CQ27G2', 45);
insert into modelo (nombre_modelo, id_marca) values ('Aurora R15 Desktop', 46);
insert into modelo (nombre_modelo, id_marca) values ('Triton 500 SE', 47);
insert into modelo (nombre_modelo, id_marca) values ('Zephyrus G14 2023', 48);
insert into modelo (nombre_modelo, id_marca) values ('FI32U 4K', 49);
insert into modelo (nombre_modelo, id_marca) values ('Cloud II Wireless', 50);
insert into modelo (nombre_modelo, id_marca) values ('Arctis Nova Pro', 51);
insert into modelo (nombre_modelo, id_marca) values ('Cintiq Pro 24', 52);
insert into modelo (nombre_modelo, id_marca) values ('Fenix 7 Sapphire Solar', 53);
insert into modelo (nombre_modelo, id_marca) values ('Charge 5', 54);
insert into modelo (nombre_modelo, id_marca) values ('QuietComfort 45', 55);

insert into sucursal (nombre_sucursal, direccion, telefono, id_comuna) values ('Sucursal Santiago Centro', 'Moneda 1140 Local 4', 933445566, 1);
insert into sucursal (nombre_sucursal, direccion, telefono, id_comuna) values ('Sucursal Providencia', 'Av. Pedro de Valdivia 520', 922334455, 2);
insert into sucursal (nombre_sucursal, direccion, telefono, id_comuna) values ('Sucursal Las Condes', 'Av. Manquehue Sur 350', 944556677, 3);
insert into sucursal (nombre_sucursal, direccion, telefono, id_comuna) values ('Sucursal La Florida', 'Av. Froilan Roa 1200', 955667788, 4);
insert into sucursal (nombre_sucursal, direccion, telefono, id_comuna) values ('Sucursal Maipu', 'Av. Pajaritos 2050', 966778899, 5);
insert into sucursal (nombre_sucursal, direccion, telefono, id_comuna) values ('Sucursal Huechuraba', 'Av. del Parque 4100', 977889900, 10);

insert into tecnico (rut, dv_run, nombre, apellido, telefono, correo, direccion, estado, id_especialidad, sueldo) values (16789452, '3', 'Carlos', 'Mendoza', 981122334, 'cmendoza.tec@tecnofix.cl', 'San Diego 890', 'Activo', 1, 850000);
insert into tecnico (rut, dv_run, nombre, apellido, telefono, correo, direccion, estado, id_especialidad, sueldo) values (18234567, '9', 'Daniela', 'Munoz', 972233445, 'dmunoz.tec@tecnofix.cl', 'Gran Avenida 4300', 'Activo', 3, 920000);
insert into tecnico (rut, dv_run, nombre, apellido, telefono, correo, direccion, estado, id_especialidad, sueldo) values (17456789, '5', 'Esteban', 'Paredes', 963344556, 'eparedes.tec@tecnofix.cl', 'Tobalaba 1450', 'Activo', 2, 780000);
insert into tecnico (rut, dv_run, nombre, apellido, telefono, correo, direccion, estado, id_especialidad, sueldo) values (15890123, '1', 'Patricia', 'Arancibia', 954455667, 'parancibia.tec@tecnofix.cl', 'Macul 2100', 'Activo', 4, 810000);
insert into tecnico (rut, dv_run, nombre, apellido, telefono, correo, direccion, estado, id_especialidad, sueldo) values (14785236, '9', 'Andres', 'Salazar', 945566778, 'asalazar.tec@tecnofix.cl', 'Rosas 1820', 'Inactivo', 3, 750000);
insert into tecnico (rut, dv_run, nombre, apellido, telefono, correo, direccion, estado, id_especialidad, sueldo) values (19012874, '2', 'Javier', 'Contreras', 936677889, 'jcontreras.tec@tecnofix.cl', 'Av. La Florida 8900', 'Activo', 5, 870000);
insert into tecnico (rut, dv_run, nombre, apellido, telefono, correo, direccion, estado, id_especialidad, sueldo) values (16450912, '8', 'Beatriz', 'Pena', 927788990, 'bpena.tec@tecnofix.cl', 'Santa Isabel 450', 'Activo', 1, 890000);
insert into tecnico (rut, dv_run, nombre, apellido, telefono, correo, direccion, estado, id_especialidad, sueldo) values (17892341, '4', 'Gonzalo', 'Tapia', 918899001, 'gtapia.tec@tecnofix.cl', 'Vespucio Norte 120', 'Activo', 3, 830000);

insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Notebook no enciende tras descarga en puerto usb', 1, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Notebook con display quebrado por presion en mochila', 3, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Portatil corporativo con lentitud y reinicios constantes', 2, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Notebook no retiene carga se apaga sin cargador', 4, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Impresora con atasco reiterado y mala calidad de color', 5, 6);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Desktop se apaga repentinamente al exigir carga de trabajo', 6, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Notebook con teclas pegadas por derrame de liquido', 2, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Portatil ultrabook sin imagen en pantalla', 7, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Servidor no bootea tras corte de suministro electrico', 10, 4);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Notebook gaming con sobrecalentamiento y ruidos en ventilador', 12, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Impresora multifuncional no tracciona hojas de bandeja', 9, 6);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('MacBook reinicia continuamente en bucle de manzana', 11, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Notebook economico con disco danado y sectores defectuosos', 8, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Workstation torre con pantalla azul de memoria ram', 6, 7);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Notebook corporativo requiere ampliacion de storage', 1, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Consola no lee discos físicos', 13, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Pantalla parpadea al iniciar SO', 14, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Teclado con switches dobles marcando', 15, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Notebook gaming sobrecalienta en reposo', 16, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Mouse con rueda de scroll trabada', 17, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Unidad m.2 no es reconocida por BIOS', 18, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Disco mecánico con clics audibles', 19, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Módulo RAM falla en test de memoria', 20, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Procesador con pines doblados', 21, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('CPU alcanza 95 grados en carga', 22, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('GPU no da video por puerto DisplayPort', 23, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Tarjeta de video con ventilador ruidoso', 24, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('GPU presenta artifacts en 3D', 25, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Placa madre con puerto USB dañado', 26, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Gabinete con panel de cristal roto', 27, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Fuente de poder hace corto al encender', 28, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Disipador con anclaje quebrado', 29, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Cooler con vibración excesiva', 30, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Torre de refrigeración sin pasta térmica', 31, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Chasis con puertos frontales sin energía', 32, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Gabinete requiere cambio de ventiladores', 33, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Memoria con RGB defectuoso', 34, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Módulos RAM no activan perfil XMP', 35, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('SSD SATA con sectores ilegibles', 36, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Unidad de estado sólido con firmware corrupto', 37, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Disco externo con conector suelto', 38, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Placa base no guarda configuración de fecha', 39, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Ultrabook no carga batería', 40, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Portátil con bisagra izquierda desprendida', 41, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Notebook apaga al desconectar de corriente', 42, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Equipo táctil con respuesta fantasma', 43, 8);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Tablet no sale del logo de inicio', 44, 8);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Monitor enciende retroiluminación sin imagen', 45, 5);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Pantalla con línea vertical verde permanente', 46, 5);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Monitor curva con filtración de luz severa', 47, 5);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Desktop corporativo con falla de red', 48, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Portátil con touchpad inoperante', 49, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Notebook con falla en chip de audio', 50, 1);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Monitor 4K no detecta señal HDMI', 51, 5);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Audífonos sin sonido en auricular derecho', 52, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Headset con micrófono quebrado', 53, 2);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Tableta digitalizadora no calibra lápiz', 54, 5);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Reloj inteligente con cristal fisurado', 55, 8);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Smartband no sincroniza bluetooth', 56, 8);
insert into equipo (descripcion, id_modelo, id_tipo_dispositivo) values ('Auriculares ANC con ruido estático', 57, 8);

insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-08-01', date '2026-08-05', date '2026-08-05', 'Revision de linea vdd en placa madre', 1, 8, 1, 1);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-08-03', date '2026-08-07', date '2026-08-08', 'Reemplazo de modulo de pantalla fhd', 2, 8, 2, 2);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-08-10', date '2026-08-14', date '2026-08-13', 'Mantencion termica profunda y limpieza interna', 3, 8, 1, 3);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-08-12', date '2026-08-18', date '2026-08-20', 'Diagnostico de celdas y reemplazo de bateria', 4, 7, 3, 4);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-08-15', date '2026-08-22', date '2026-08-25', 'Desarme y calibracion de inyectores piezo', 5, 6, 4, 5);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-08-18', date '2026-08-23', date '2026-08-26', 'Pruebas de estres de fuente de poder atx', 6, 5, 1, 6);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-08-20', date '2026-08-24', date '2026-08-25', 'Limpieza quimica de teclado y ensamble', 7, 7, 2, 7);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-08-22', date '2026-08-27', date '2026-08-29', 'Cambio de disipador y thermal pads', 9, 6, 4, 10);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-08-24', date '2026-08-28', date '2026-08-30', 'Sustitucion de rodillo y mantenimiento', 11, 7, 5, 11);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-08-25', date '2026-08-28', date '2026-09-02', 'Revision circuito inversor de iluminacion', 1, 6, 3, 8);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-08-26', date '2026-08-30', date '2026-09-03', 'Reparacion de pistas y recuperacion de boot', 10, 9, 2, 12);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-08-27', date '2026-08-30', date '2026-09-04', 'Diagnostico raid y recuperacion de volumen', 8, 3, 1, 9);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-08-28', date '2026-09-01', date '2026-09-03', 'Migracion a disco solido y mantencion', 12, 6, 5, 13);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-08-29', date '2026-09-03', date '2026-09-05', 'Testeo de bancos de ram y reemplazo', 8, 2, 6, 14);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-08-30', date '2026-09-04', date '2026-09-06', 'Upgrade de almacenamiento corporativo', 3, 1, 3, 15);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-01', date '2026-09-05', null, 'Recepcion para diagnostico de lector', 13, 1, 1, 16);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-01', date '2026-09-06', null, 'Revision de pantalla y flex', 14, 1, 2, 17);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-02', date '2026-09-05', null, 'Limpieza y testeo de switches', 15, 1, 3, 18);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-02', date '2026-09-07', null, 'Mantenimiento termico y repasteo', 16, 1, 4, 19);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-03', date '2026-09-05', null, 'Desarme y destrabe de rueda', 17, 1, 5, 20);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-03', date '2026-09-06', null, 'Pruebas logicas en puerto m.2', 18, 1, 6, 21);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-04', date '2026-09-08', null, 'Evaluacion de sectores y cabezal', 19, 1, 1, 22);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-04', date '2026-09-06', null, 'Stress test de memorias RAM', 20, 1, 2, 23);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-05', date '2026-09-09', null, 'Alineacion micrometrica de pines', 21, 1, 3, 24);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-05', date '2026-09-08', null, 'Test de estres y temperaturas', 22, 1, 4, 25);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-06', date '2026-09-10', null, 'Revision de puertos de video', 23, 1, 5, 26);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-06', date '2026-09-09', null, 'Lubricacion y cambio de ventilador', 24, 1, 6, 27);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-07', date '2026-09-12', null, 'Diagnostico de chips de VRAM', 25, 1, 1, 28);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-07', date '2026-09-10', null, 'Microsoldadura de puerto USB', 26, 1, 2, 29);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-08', date '2026-09-13', null, 'Retiro de esquirlas y recambio', 27, 1, 3, 30);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-08', date '2026-09-11', null, 'Testeo de rieles de voltaje', 28, 1, 4, 31);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-09', date '2026-09-14', null, 'Montaje de anclaje de reemplazo', 29, 1, 5, 32);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-09', date '2026-09-12', null, 'Revision de rodamientos', 30, 1, 6, 33);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-10', date '2026-09-15', null, 'Aplicacion de compuesto termico', 31, 1, 1, 34);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-10', date '2026-09-13', null, 'Verificacion de cables de panel frontal', 32, 1, 2, 35);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-11', date '2026-09-16', null, 'Instalacion de pack de fans', 33, 1, 3, 36);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-11', date '2026-09-14', null, 'Flasheo de controlador RGB', 34, 1, 4, 37);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-12', date '2026-09-17', null, 'Prueba de compatibilidad en placa', 35, 1, 5, 38);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-12', date '2026-09-15', null, 'Recuperacion logica y descarte', 36, 1, 6, 39);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-13', date '2026-09-18', null, 'Actualizacion forzada de firmware', 37, 1, 1, 40);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-13', date '2026-09-16', null, 'Resoldado de conector USB-C', 38, 1, 2, 41);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-14', date '2026-09-19', null, 'Cambio de bateria CMOS', 39, 1, 3, 42);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-14', date '2026-09-17', null, 'Testeo de pin de carga', 40, 1, 4, 43);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-15', date '2026-09-20', null, 'Reparacion de anclaje de bisagra', 41, 1, 5, 44);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-15', date '2026-09-18', null, 'Sustitucion de bateria interna', 42, 1, 6, 45);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-16', date '2026-09-21', null, 'Calibracion de digitalizador', 43, 1, 1, 46);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-16', date '2026-09-19', null, 'Reinstalacion de software de sistema', 44, 1, 2, 47);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-17', date '2026-09-22', null, 'Revision de placa T-CON', 45, 1, 3, 48);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-17', date '2026-09-20', null, 'Cambio de display completo', 46, 1, 4, 49);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-18', date '2026-09-23', null, 'Ajuste de ensamblaje de panel', 47, 1, 5, 50);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-18', date '2026-09-21', null, 'Actualizacion de tarjeta de red', 48, 1, 6, 51);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-19', date '2026-09-24', null, 'Revision de flex de touchpad', 49, 1, 1, 52);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-19', date '2026-09-22', null, 'Microsoldadura de codec de audio', 50, 1, 2, 53);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-20', date '2026-09-25', null, 'Test de placa logica del monitor', 51, 1, 3, 54);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-20', date '2026-09-23', null, 'Sustitucion de parlante interno', 52, 1, 4, 55);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-21', date '2026-09-26', null, 'Reemplazo de modulo de microfono', 53, 1, 5, 56);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-21', date '2026-09-24', null, 'Actualizacion de firmware de digitalizador', 54, 1, 6, 57);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-22', date '2026-09-27', null, 'Cambio de pantalla de smartwatch', 55, 1, 1, 58);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-22', date '2026-09-25', null, 'Flasheo de ROM de banda', 56, 1, 2, 59);
insert into orden (fecha_recepcion, fecha_estimada, fecha_entrega, descripcion, id_cliente, id_estado_orden, id_sucursal, id_equipo) values (date '2026-09-23', date '2026-09-28', null, 'Limpieza de circuitos ANC', 57, 1, 3, 60);

insert into reparacion (fecha_inicio, fecha_finalizacion, diagnostico, descripcion, id_orden, id_tecnico) values (date '2026-08-02', date '2026-08-04', 'Mosfet entrada quemado', 'Reemplazo de componente mosfet de 19v y bypass de proteccion', 1, 1);
insert into reparacion (fecha_inicio, fecha_finalizacion, diagnostico, descripcion, id_orden, id_tecnico) values (date '2026-08-04', date '2026-08-07', 'Panel fhd quebrado', 'Instalacion de repuesto original y prueba de tasas de refresco', 2, 2);
insert into reparacion (fecha_inicio, fecha_finalizacion, diagnostico, descripcion, id_orden, id_tecnico) values (date '2026-08-11', date '2026-08-12', 'Compuesto termico solidificado', 'Limpieza profunda de disipador y sustitucion de pasta termica', 3, 2);
insert into reparacion (fecha_inicio, fecha_finalizacion, diagnostico, descripcion, id_orden, id_tecnico) values (date '2026-08-13', date '2026-08-17', 'Bateria con celdas hinchadas', 'Sustitucion de bateria macbook y calibracion de ciclo smc', 4, 1);
insert into reparacion (fecha_inicio, fecha_finalizacion, diagnostico, descripcion, id_orden, id_tecnico) values (date '2026-08-16', date '2026-08-21', 'Cabezal con conductos tapados', 'Desobstruccion por ultrasonido y reemplazo de cabezal epson', 5, 4);
insert into reparacion (fecha_inicio, fecha_finalizacion, diagnostico, descripcion, id_orden, id_tecnico) values (date '2026-08-19', date '2026-08-22', 'Riel de 12v con caida de voltaje', 'Desmontaje de fuente defectuosa a la espera de stock de reemplazo', 6, 2);
insert into reparacion (fecha_inicio, fecha_finalizacion, diagnostico, descripcion, id_orden, id_tecnico) values (date '2026-08-21', date '2026-08-23', 'Teclas pegadas con sulfato', 'Montaje de nuevo teclado thinkpad y pruebas de continuidad', 7, 2);
insert into reparacion (fecha_inicio, fecha_finalizacion, diagnostico, descripcion, id_orden, id_tecnico) values (date '2026-08-23', date '2026-08-26', 'Cooler con rodamiento quebrado', 'Instalacion de cooler nuevo original hp y repasteo', 8, 8);
insert into reparacion (fecha_inicio, fecha_finalizacion, diagnostico, descripcion, id_orden, id_tecnico) values (date '2026-08-25', date '2026-08-27', 'Rodillo gastado y deformado', 'Cambio kit arrastre brother y calibracion de sensores opticos', 9, 4);
insert into reparacion (fecha_inicio, fecha_finalizacion, diagnostico, descripcion, id_orden, id_tecnico) values (date '2026-08-26', date '2026-08-29', 'Circuito backlight desoldado', 'Microsoldadura en conector fpc de pantalla asus', 10, 7);
insert into reparacion (fecha_inicio, fecha_finalizacion, diagnostico, descripcion, id_orden, id_tecnico) values (date '2026-08-27', date '2026-08-29', 'Corrupcion nand irreversible', 'Revision de pistas en placa logica sin posibilidad de salvar nand', 11, 7);
insert into reparacion (fecha_inicio, fecha_finalizacion, diagnostico, descripcion, id_orden, id_tecnico) values (date '2026-08-28', date '2026-08-31', 'Disco mecanico con sectores', 'Clonacion hacia disco solido sata e instalacion interna', 13, 3);
insert into reparacion (fecha_inicio, fecha_finalizacion, diagnostico, descripcion, id_orden, id_tecnico) values (date '2026-08-30', date '2026-09-01', 'Modulo ram con fallas de paridad', 'Sustitucion de memoria ddr4 de 16gb y prueba memtest86', 14, 6);

insert into repuesto_utilizado (id_reparacion, id_repuesto, cantidad_utilizada) values (1, 4, 1);
insert into repuesto_utilizado (id_reparacion, id_repuesto, cantidad_utilizada) values (2, 2, 1);
insert into repuesto_utilizado (id_reparacion, id_repuesto, cantidad_utilizada) values (3, 4, 1);
insert into repuesto_utilizado (id_reparacion, id_repuesto, cantidad_utilizada) values (4, 5, 1);
insert into repuesto_utilizado (id_reparacion, id_repuesto, cantidad_utilizada) values (5, 6, 1);
insert into repuesto_utilizado (id_reparacion, id_repuesto, cantidad_utilizada) values (7, 7, 1);
insert into repuesto_utilizado (id_reparacion, id_repuesto, cantidad_utilizada) values (8, 4, 1);
insert into repuesto_utilizado (id_reparacion, id_repuesto, cantidad_utilizada) values (8, 11, 1);
insert into repuesto_utilizado (id_reparacion, id_repuesto, cantidad_utilizada) values (9, 12, 1);
insert into repuesto_utilizado (id_reparacion, id_repuesto, cantidad_utilizada) values (12, 9, 1);
insert into repuesto_utilizado (id_reparacion, id_repuesto, cantidad_utilizada) values (12, 3, 1);

commit;